In [1]:
#Image1.png(acetone) : %conc. of acetone
ax0,ay0=38,33
ax_max,ay_max=278,213
ax_range=7
ay_range=8
ax_ZnO=[68,97,125,157,187,215,247,276]
ay_ZnO=[55,59,75,119,161,184,192,201]
ax_SnO2=[67,97,125,157,187,216,246,277]
ay_SnO2=[60,62,74,85,107,108,107,108]
ax_CdS=[68,97,125,155,186,215,247,277]
ay_CdS=[51,50,50,48,48,46,45,44]
ax_MoO=[68,97,127,159,187,216,247,277]
ay_MoO=[54,57,58,66,76,78,77,76]

In [2]:
#Image2.png(Ccl4) : %conc. of ccl4
cx0,cy0=64,58
cx_max,cy_max=469,343
cx_range=2.5
cy_range=40
cx_ZnO=[101,143,184,224,267,307,347,388,428,466]
cy_ZnO=[68,78,87,87,92,95,111,119,124,133]
cx_SnO2=[103,143,184,224,264,305,345,386,424,464]
cy_SnO2=[87,117,153,186,227,234,265,287,308,326]
cx_MoO=[101,144,185,225,266,306,348,390,428,468]
cy_MoO=[63,69,72,72,77,78,83,88,90,90]
cx_CdS=[101,144,185,225,266,308,348,389,428,467]
cy_CdS=[61,63,66,66,71,72,76,80,83,84]

In [3]:
#Image3.png(emk) : %conc. of emk
ex0,ey0=38,32
ex_max,ey_max=275,208
ex_range=8
ey_range=10
ex_ZnO=[55,73,92,110,128,146,164,183,200,219,236,255]
ey_ZnO=[58,68,73,90,104,123,135,143,162,178,198,201]
ex_SnO2=[56,74,91,109,127,146,164,183,200,219,237,255]
ey_SnO2=[44,54,66,83,96,113,127,139,158,174,187,197]
ex_CdS=[56,75,92,111,129,147,166,184,202,220,239,255]
ey_CdS=[35,36,38,38,41,44,44,45,47,49,51,51]
ex_MoO=[56,74,91,111,129,146,164,183,202,219,238,256]
ey_MoO=[37,40,42,46,49,52,56,58,60,64,68,69]

In [4]:
#Image4.png(xylene) : %conc. of xylene
xx0,xy0=43,32
xx_max,xy_max=285,211
xx_range=6
xy_range=30
xx_ZnO=[64,85,105,124,144,166,186,205,226,245,266,284]
xy_ZnO=[34,35,35,36,38,41,42,46,47,51,56,59]
xx_SnO2=[63,86,105,125,144,164,185,203,224,2243,263,283]
xy_SnO2=[42,49,67,81,95,109,124,136,156,171,182,202]
xx_CdS=[64,84,104,125,145,166,185,205,225,245,265,285]
xy_CdS=[35,37,39,40,41,44,45,49,51,54,53,56]
xx_MoO=[64,85,104,124,145,165,185,206,224,246,267,285]
xy_MoO=[32,33,34,34,34,34,35,37,37,39,38,41]

In [5]:
from pandas import DataFrame
def convertt(x_c,y_c,x0,y0,x_max,y_max,x_range,y_range):
    conc=[]
    resp=[]
    for xi,yi in zip(x_c,y_c):
        xit,yit=xi-x0,yi-y0
        conc_xi=xit/((x_max-x0)/(x_range))
        resp_yi=yit/((y_max-y0)/(y_range))
        conc.append(conc_xi)
        resp.append(resp_yi)
    return conc,resp

In [6]:
conc_z,resp_z=convertt(ax_ZnO,ay_ZnO,ax0,ay0,ax_max,ay_max,ax_range,ay_range)
conc_m,resp_m=convertt(ax_MoO,ay_MoO,ax0,ay0,ax_max,ay_max,ax_range,ay_range)
conc_c,resp_c=convertt(ax_CdS,ay_CdS,ax0,ay0,ax_max,ay_max,ax_range,ay_range)
conc_s,resp_s=convertt(ax_SnO2,ay_SnO2,ax0,ay0,ax_max,ay_max,ax_range,ay_range)
acetone=DataFrame()
acetone["Conc_Zn"]=conc_z
acetone["resp_Zn"]=resp_z
acetone["Conc_Cd"]=conc_c
acetone["resp_Cd"]=resp_c
acetone["Conc_Mo"]=conc_m
acetone["resp_Mo"]=resp_m
acetone["Conc_Sn"]=conc_s
acetone["resp_Sn"]=resp_s
acetone

,Conc_Zn,resp_Zn,Conc_Cd,resp_Cd,Conc_Mo,resp_Mo,Conc_Sn,resp_Sn
0,0.875000,0.977778,0.875000,0.800000,0.875000,0.933333,0.845833,1.200000
1,1.720833,1.155556,1.720833,0.755556,1.720833,1.066667,1.720833,1.288889
2,2.537500,1.866667,2.537500,0.755556,2.595833,1.111111,2.537500,1.822222
3,3.470833,3.822222,3.412500,0.666667,3.529167,1.466667,3.470833,2.311111
4,4.345833,5.688889,4.316667,0.666667,4.345833,1.911111,4.345833,3.288889
5,5.162500,6.711111,5.162500,0.577778,5.191667,2.000000,5.191667,3.333333
6,6.095833,7.066667,6.095833,0.533333,6.095833,1.955556,6.066667,3.288889
7,6.941667,7.466667,6.970833,0.488889,6.970833,1.911111,6.970833,3.333333

In [7]:
conc_z,resp_z=convertt(cx_ZnO,cy_ZnO,cx0,cy0,cx_max,cy_max,cx_range,cy_range)
conc_m,resp_m=convertt(cx_MoO,cy_MoO,cx0,cy0,cx_max,cy_max,cx_range,cy_range)
conc_c,resp_c=convertt(cx_CdS,cy_CdS,cx0,cy0,cx_max,cy_max,cx_range,cy_range)
conc_s,resp_s=convertt(cx_SnO2,cy_SnO2,cx0,cy0,cx_max,cy_max,cx_range,cy_range)
ccl4=DataFrame()
ccl4["Conc_Zn"]=conc_z
ccl4["resp_Zn"]=resp_z
ccl4["Conc_Cd"]=conc_c
ccl4["resp_Cd"]=resp_c
ccl4["Conc_Mo"]=conc_m
ccl4["resp_Mo"]=resp_m
ccl4["Conc_Sn"]=conc_s
ccl4["resp_Sn"]=resp_s
ccl4

,Conc_Zn,resp_Zn,Conc_Cd,resp_Cd,Conc_Mo,resp_Mo,Conc_Sn,resp_Sn
0,0.228395,1.403509,0.228395,0.421053,0.228395,0.701754,0.240741,4.070175
1,0.487654,2.807018,0.493827,0.701754,0.493827,1.543860,0.487654,8.280702
2,0.740741,4.070175,0.746914,1.122807,0.746914,1.964912,0.740741,13.333333
3,0.987654,4.070175,0.993827,1.122807,0.993827,1.964912,0.987654,17.964912
4,1.253086,4.771930,1.246914,1.824561,1.246914,2.666667,1.234568,23.719298
5,1.500000,5.192982,1.506173,1.964912,1.493827,2.807018,1.487654,24.701754
6,1.746914,7.438596,1.753086,2.526316,1.753086,3.508772,1.734568,29.052632
7,2.000000,8.561404,2.006173,3.087719,2.012346,4.210526,1.987654,32.140351
8,2.246914,9.263158,2.246914,3.508772,2.246914,4.491228,2.222222,35.087719
9,2.481481,10.526316,2.487654,3.649123,2.493827,4.491228,2.469136,37.614035

In [8]:
conc_z,resp_z=convertt(ex_ZnO,ey_ZnO,ex0,ey0,ex_max,ey_max,ex_range,ey_range)
conc_m,resp_m=convertt(ex_MoO,ey_MoO,ex0,ey0,ex_max,ey_max,ex_range,ey_range)
conc_c,resp_c=convertt(ex_CdS,ey_CdS,ex0,ey0,ex_max,ey_max,ex_range,ey_range)
conc_s,resp_s=convertt(ex_SnO2,ey_SnO2,ex0,ey0,ex_max,ey_max,ex_range,ey_range)
emk=DataFrame()
emk["Conc_Zn"]=conc_z
emk["resp_Zn"]=resp_z
emk["Conc_Cd"]=conc_c
emk["resp_Cd"]=resp_c
emk["Conc_Mo"]=conc_m
emk["resp_Mo"]=resp_m
emk["Conc_Sn"]=conc_s
emk["resp_Sn"]=resp_s
emk

,Conc_Zn,resp_Zn,Conc_Cd,resp_Cd,Conc_Mo,resp_Mo,Conc_Sn,resp_Sn
0,0.573840,1.477273,0.607595,0.170455,0.607595,0.284091,0.607595,0.681818
1,1.181435,2.045455,1.248945,0.227273,1.215190,0.454545,1.215190,1.250000
2,1.822785,2.329545,1.822785,0.340909,1.789030,0.568182,1.789030,1.931818
3,2.430380,3.295455,2.464135,0.340909,2.464135,0.795455,2.396624,2.897727
4,3.037975,4.090909,3.071730,0.511364,3.071730,0.965909,3.004219,3.636364
5,3.645570,5.170455,3.679325,0.681818,3.645570,1.136364,3.645570,4.602273
6,4.253165,5.852273,4.320675,0.681818,4.253165,1.363636,4.253165,5.397727
7,4.894515,6.306818,4.928270,0.738636,4.894515,1.477273,4.894515,6.079545
8,5.468354,7.386364,5.535865,0.852273,5.535865,1.590909,5.468354,7.159091
9,6.109705,8.295455,6.143460,0.965909,6.109705,1.818182,6.109705,8.068182
10,6.683544,9.431818,6.784810,1.079545,6.751055,2.045455,6.717300,8.806818
11,7.324895,9.602273,7.324895,1.079545,7.358650,2.102273,7.324895,9.375000

In [9]:
conc_z,resp_z=convertt(xx_ZnO,xy_ZnO,xx0,xy0,xx_max,xy_max,xx_range,xy_range)
conc_m,resp_m=convertt(xx_MoO,xy_MoO,xx0,xy0,xx_max,xy_max,xx_range,xy_range)
conc_c,resp_c=convertt(xx_CdS,xy_CdS,xx0,xy0,xx_max,xy_max,xx_range,xy_range)
conc_s,resp_s=convertt(xx_SnO2,xy_SnO2,xx0,xy0,xx_max,xy_max,xx_range,xy_range)
xylene=DataFrame()
xylene["Conc_Zn"]=conc_z
xylene["resp_Zn"]=resp_z
xylene["Conc_Cd"]=conc_c
xylene["resp_Cd"]=resp_c
xylene["Conc_Mo"]=conc_m
xylene["resp_Mo"]=resp_m
xylene["Conc_Sn"]=conc_s
xylene["resp_Sn"]=resp_s
xylene

,Conc_Zn,resp_Zn,Conc_Cd,resp_Cd,Conc_Mo,resp_Mo,Conc_Sn,resp_Sn
0,0.520661,0.335196,0.520661,0.502793,0.520661,0.000000,0.495868,1.675978
1,1.041322,0.502793,1.016529,0.837989,1.041322,0.167598,1.066116,2.849162
2,1.537190,0.502793,1.512397,1.173184,1.512397,0.335196,1.537190,5.865922
3,2.008264,0.670391,2.033058,1.340782,2.008264,0.335196,2.033058,8.212291
4,2.504132,1.005587,2.528926,1.508380,2.528926,0.335196,2.504132,10.558659
5,3.049587,1.508380,3.049587,2.011173,3.024793,0.335196,3.000000,12.905028
6,3.545455,1.675978,3.520661,2.178771,3.520661,0.502793,3.520661,15.418994
7,4.016529,2.346369,4.016529,2.849162,4.041322,0.837989,3.966942,17.430168
8,4.537190,2.513966,4.512397,3.184358,4.487603,0.837989,4.487603,20.782123
9,5.008264,3.184358,5.008264,3.687151,5.033058,1.173184,54.545455,23.296089
10,5.528926,4.022346,5.504132,3.519553,5.553719,1.005587,5.454545,25.139665
11,5.975207,4.525140,6.000000,4.022346,6.000000,1.508380,5.950413,28.491620